package table

var x072 = [][]uint8{
	[]uint8("He "),           // 0x00
	[]uint8("Lan "),          // 0x01
	[]uint8("Biao "),         // 0x02
	[]uint8("Rong "),         // 0x03
	[]uint8("Li "),           // 0x04
	[]uint8("Mo "),           // 0x05
	[]uint8("Bao "),          // 0x06
	[]uint8("Ruo "),          // 0x07
	[]uint8("Lu "),           // 0x08
	[]uint8("La "),           // 0x09
	[]uint8("Ao "),           // 0x0a
	[]uint8("Xun "),          // 0x0b
	[]uint8("Kuang "),        // 0x0c
	[]uint8("Shuo "),         // 0x0d
	[]uint8("[?] "),          // 0x0e
	[]uint8("Li "),           // 0x0f
	[]uint8("Lu "),           // 0x10
	[]uint8("Jue "),          // 0x11
	[]uint8("Liao "),         // 0x12
	[]uint8("Yan "),          // 0x13
	[]uint8("Xi "),           // 0x14
	[]uint8("Xie "),          // 0x15
	[]uint8("Long "),         // 0x16
	[]uint8("Ye "),           // 0x17
	[]uint8("[?] "),          // 0x18
	[]uint8("Rang "),         // 0x19
	[]uint8("Yue "),          // 0x1a
	[]uint8("Lan "),          // 0x1b
	[]uint8("Cong "),         // 0x1c
	[]uint8("Jue "),          // 0x1d
	[]uint8("Tong "),         // 0x1e
	[]uint8("Guan "),         // 0x1f
	[]uint8("[?] "),          // 0x20
	[]uint8("Che "),          // 0x21
	[]uint8("Mi "),           // 0x22
	[]uint8("Tang "),         // 0x23
	[]uint8("Lan "),          // 0x24
	[]uint8("Zhu "),          // 0x25
	[]uint8("[?] "),          // 0x26
	[]uint8("Ling "),         // 0x27
	[]uint8("Cuan "),         // 0x28
	[]uint8("Yu "),           // 0x29
	[]uint8("Zhua "),         // 0x2a
	"Tsumekanmuri ", // 0x2b
	[]uint8("Pa "),           // 0x2c
	[]uint8("Zheng "),        // 0x2d
	[]uint8("Pao "),          // 0x2e
	[]uint8("Cheng "),        // 0x2f
	[]uint8("Yuan "),         // 0x30
	[]uint8("Ai "),           // 0x31
	[]uint8("Wei "),          // 0x32
	[]uint8("[?] "),          // 0x33
	[]uint8("Jue "),          // 0x34
	[]uint8("Jue "),          // 0x35
	[]uint8("Fu "),           // 0x36
	[]uint8("Ye "),           // 0x37
	[]uint8("Ba "),           // 0x38
	[]uint8("Die "),          // 0x39
	[]uint8("Ye "),           // 0x3a
	[]uint8("Yao "),          // 0x3b
	[]uint8("Zu "),           // 0x3c
	[]uint8("Shuang "),       // 0x3d
	[]uint8("Er "),           // 0x3e
	[]uint8("Qiang "),        // 0x3f
	[]uint8("Chuang "),       // 0x40
	[]uint8("Ge "),           // 0x41
	[]uint8("Zang "),         // 0x42
	[]uint8("Die "),          // 0x43
	[]uint8("Qiang "),        // 0x44
	[]uint8("Yong "),         // 0x45
	[]uint8("Qiang "),        // 0x46
	[]uint8("Pian "),         // 0x47
	[]uint8("Ban "),          // 0x48
	[]uint8("Pan "),          // 0x49
	[]uint8("Shao "),         // 0x4a
	[]uint8("Jian "),         // 0x4b
	[]uint8("Pai "),          // 0x4c
	[]uint8("Du "),           // 0x4d
	[]uint8("Chuang "),       // 0x4e
	[]uint8("Tou "),          // 0x4f
	[]uint8("Zha "),          // 0x50
	[]uint8("Bian "),         // 0x51
	[]uint8("Die "),          // 0x52
	[]uint8("Bang "),         // 0x53
	[]uint8("Bo "),           // 0x54
	[]uint8("Chuang "),       // 0x55
	[]uint8("You "),          // 0x56
	[]uint8("[?] "),          // 0x57
	[]uint8("Du "),           // 0x58
	[]uint8("Ya "),           // 0x59
	[]uint8("Cheng "),        // 0x5a
	[]uint8("Niu "),          // 0x5b
	[]uint8("Ushihen "),      // 0x5c
	[]uint8("Pin "),          // 0x5d
	[]uint8("Jiu "),          // 0x5e
	[]uint8("Mou "),          // 0x5f
	[]uint8("Tuo "),          // 0x60
	[]uint8("Mu "),           // 0x61
	[]uint8("Lao "),          // 0x62
	[]uint8("Ren "),          // 0x63
	[]uint8("Mang "),         // 0x64
	[]uint8("Fang "),         // 0x65
	[]uint8("Mao "),          // 0x66
	[]uint8("Mu "),           // 0x67
	[]uint8("Gang "),         // 0x68
	[]uint8("Wu "),           // 0x69
	[]uint8("Yan "),          // 0x6a
	[]uint8("Ge "),           // 0x6b
	[]uint8("Bei "),          // 0x6c
	[]uint8("Si "),           // 0x6d
	[]uint8("Jian "),         // 0x6e
	[]uint8("Gu "),           // 0x6f
	[]uint8("You "),          // 0x70
	[]uint8("Ge "),           // 0x71
	[]uint8("Sheng "),        // 0x72
	[]uint8("Mu "),           // 0x73
	[]uint8("Di "),           // 0x74
	[]uint8("Qian "),         // 0x75
	[]uint8("Quan "),         // 0x76
	[]uint8("Quan "),         // 0x77
	[]uint8("Zi "),           // 0x78
	[]uint8("Te "),           // 0x79
	[]uint8("Xi "),           // 0x7a
	[]uint8("Mang "),         // 0x7b
	[]uint8("Keng "),         // 0x7c
	[]uint8("Qian "),         // 0x7d
	[]uint8("Wu "),           // 0x7e
	[]uint8("Gu "),           // 0x7f
	[]uint8("Xi "),           // 0x80
	[]uint8("Li "),           // 0x81
	[]uint8("Li "),           // 0x82
	[]uint8("Pou "),          // 0x83
	[]uint8("Ji "),           // 0x84
	[]uint8("Gang "),         // 0x85
	[]uint8("Zhi "),          // 0x86
	[]uint8("Ben "),          // 0x87
	[]uint8("Quan "),         // 0x88
	[]uint8("Run "),          // 0x89
	[]uint8("Du "),           // 0x8a
	[]uint8("Ju "),           // 0x8b
	[]uint8("Jia "),          // 0x8c
	[]uint8("Jian "),         // 0x8d
	[]uint8("Feng "),         // 0x8e
	[]uint8("Pian "),         // 0x8f
	[]uint8("Ke "),           // 0x90
	[]uint8("Ju "),           // 0x91
	[]uint8("Kao "),          // 0x92
	[]uint8("Chu "),          // 0x93
	[]uint8("Xi "),           // 0x94
	[]uint8("Bei "),          // 0x95
	[]uint8("Luo "),          // 0x96
	[]uint8("Jie "),          // 0x97
	[]uint8("Ma "),           // 0x98
	[]uint8("San "),          // 0x99
	[]uint8("Wei "),          // 0x9a
	[]uint8("Li "),           // 0x9b
	[]uint8("Dun "),          // 0x9c
	[]uint8("Tong "),         // 0x9d
	[]uint8("[?] "),          // 0x9e
	[]uint8("Jiang "),        // 0x9f
	[]uint8("Ikenie "),       // 0xa0
	[]uint8("Li "),           // 0xa1
	[]uint8("Du "),           // 0xa2
	[]uint8("Lie "),          // 0xa3
	[]uint8("Pi "),           // 0xa4
	[]uint8("Piao "),         // 0xa5
	[]uint8("Bao "),          // 0xa6
	[]uint8("Xi "),           // 0xa7
	[]uint8("Chou "),         // 0xa8
	[]uint8("Wei "),          // 0xa9
	[]uint8("Kui "),          // 0xaa
	[]uint8("Chou "),         // 0xab
	[]uint8("Quan "),         // 0xac
	[]uint8("Fan "),          // 0xad
	[]uint8("Ba "),           // 0xae
	[]uint8("Fan "),          // 0xaf
	[]uint8("Qiu "),          // 0xb0
	[]uint8("Ji "),           // 0xb1
	[]uint8("Cai "),          // 0xb2
	[]uint8("Chuo "),         // 0xb3
	[]uint8("An "),           // 0xb4
	[]uint8("Jie "),          // 0xb5
	[]uint8("Zhuang "),       // 0xb6
	[]uint8("Guang "),        // 0xb7
	[]uint8("Ma "),           // 0xb8
	[]uint8("You "),          // 0xb9
	[]uint8("Kang "),         // 0xba
	[]uint8("Bo "),           // 0xbb
	[]uint8("Hou "),          // 0xbc
	[]uint8("Ya "),           // 0xbd
	[]uint8("Yin "),          // 0xbe
	[]uint8("Huan "),         // 0xbf
	[]uint8("Zhuang "),       // 0xc0
	[]uint8("Yun "),          // 0xc1
	[]uint8("Kuang "),        // 0xc2
	[]uint8("Niu "),          // 0xc3
	[]uint8("Di "),           // 0xc4
	[]uint8("Qing "),         // 0xc5
	[]uint8("Zhong "),        // 0xc6
	[]uint8("Mu "),           // 0xc7
	[]uint8("Bei "),          // 0xc8
	[]uint8("Pi "),           // 0xc9
	[]uint8("Ju "),           // 0xca
	[]uint8("Ni "),           // 0xcb
	[]uint8("Sheng "),        // 0xcc
	[]uint8("Pao "),          // 0xcd
	[]uint8("Xia "),          // 0xce
	[]uint8("Tuo "),          // 0xcf
	[]uint8("Hu "),           // 0xd0
	[]uint8("Ling "),         // 0xd1
	[]uint8("Fei "),          // 0xd2
	[]uint8("Pi "),           // 0xd3
	[]uint8("Ni "),           // 0xd4
	[]uint8("Ao "),           // 0xd5
	[]uint8("You "),          // 0xd6
	[]uint8("Gou "),          // 0xd7
	[]uint8("Yue "),          // 0xd8
	[]uint8("Ju "),           // 0xd9
	[]uint8("Dan "),          // 0xda
	[]uint8("Po "),           // 0xdb
	[]uint8("Gu "),           // 0xdc
	[]uint8("Xian "),         // 0xdd
	[]uint8("Ning "),         // 0xde
	[]uint8("Huan "),         // 0xdf
	[]uint8("Hen "),          // 0xe0
	[]uint8("Jiao "),         // 0xe1
	[]uint8("He "),           // 0xe2
	[]uint8("Zhao "),         // 0xe3
	[]uint8("Ji "),           // 0xe4
	[]uint8("Xun "),          // 0xe5
	[]uint8("Shan "),         // 0xe6
	[]uint8("Ta "),           // 0xe7
	[]uint8("Rong "),         // 0xe8
	[]uint8("Shou "),         // 0xe9
	[]uint8("Tong "),         // 0xea
	[]uint8("Lao "),          // 0xeb
	[]uint8("Du "),           // 0xec
	[]uint8("Xia "),          // 0xed
	[]uint8("Shi "),          // 0xee
	[]uint8("Hua "),          // 0xef
	[]uint8("Zheng "),        // 0xf0
	[]uint8("Yu "),           // 0xf1
	[]uint8("Sun "),          // 0xf2
	[]uint8("Yu "),           // 0xf3
	[]uint8("Bi "),           // 0xf4
	[]uint8("Mang "),         // 0xf5
	[]uint8("Xi "),           // 0xf6
	[]uint8("Juan "),         // 0xf7
	[]uint8("Li "),           // 0xf8
	[]uint8("Xia "),          // 0xf9
	[]uint8("Yin "),          // 0xfa
	[]uint8("Suan "),         // 0xfb
	[]uint8("Lang "),         // 0xfc
	[]uint8("Bei "),          // 0xfd
	[]uint8("Zhi "),          // 0xfe
	[]uint8("Yan "),          // 0xff
}
