package table

var x074 = [][]uint8{
	[]uint8("Han "),         // 0x00
	[]uint8("Xuan "),        // 0x01
	[]uint8("Yan "),         // 0x02
	[]uint8("Qiu "),         // 0x03
	[]uint8("Quan "),        // 0x04
	[]uint8("Lang "),        // 0x05
	[]uint8("Li "),          // 0x06
	[]uint8("Xiu "),         // 0x07
	[]uint8("Fu "),          // 0x08
	[]uint8("Liu "),         // 0x09
	[]uint8("Ye "),          // 0x0a
	[]uint8("Xi "),          // 0x0b
	[]uint8("Ling "),        // 0x0c
	[]uint8("Li "),          // 0x0d
	[]uint8("Jin "),         // 0x0e
	[]uint8("Lian "),        // 0x0f
	[]uint8("Suo "),         // 0x10
	[]uint8("Chiisai "),     // 0x11
	[]uint8("[?] "),         // 0x12
	[]uint8("Wan "),         // 0x13
	[]uint8("Dian "),        // 0x14
	[]uint8("Pin "),         // 0x15
	[]uint8("Zhan "),        // 0x16
	[]uint8("Cui "),         // 0x17
	[]uint8("Min "),         // 0x18
	[]uint8("Yu "),          // 0x19
	[]uint8("Ju "),          // 0x1a
	[]uint8("Chen "),        // 0x1b
	[]uint8("Lai "),         // 0x1c
	[]uint8("Wen "),         // 0x1d
	[]uint8("Sheng "),       // 0x1e
	[]uint8("Wei "),         // 0x1f
	[]uint8("Dian "),        // 0x20
	[]uint8("Chu "),         // 0x21
	[]uint8("Zhuo "),        // 0x22
	[]uint8("Pei "),         // 0x23
	[]uint8("Cheng "),       // 0x24
	[]uint8("Hu "),          // 0x25
	[]uint8("Qi "),          // 0x26
	[]uint8("E "),           // 0x27
	[]uint8("Kun "),         // 0x28
	[]uint8("Chang "),       // 0x29
	[]uint8("Qi "),          // 0x2a
	[]uint8("Beng "),        // 0x2b
	[]uint8("Wan "),         // 0x2c
	[]uint8("Lu "),          // 0x2d
	[]uint8("Cong "),        // 0x2e
	[]uint8("Guan "),        // 0x2f
	[]uint8("Yan "),         // 0x30
	[]uint8("Diao "),        // 0x31
	[]uint8("Bei "),         // 0x32
	[]uint8("Lin "),         // 0x33
	[]uint8("Qin "),         // 0x34
	[]uint8("Pi "),          // 0x35
	[]uint8("Pa "),          // 0x36
	[]uint8("Que "),         // 0x37
	[]uint8("Zhuo "),        // 0x38
	[]uint8("Qin "),         // 0x39
	[]uint8("Fa "),          // 0x3a
	[]uint8("[?] "),         // 0x3b
	[]uint8("Qiong "),       // 0x3c
	[]uint8("Du "),          // 0x3d
	[]uint8("Jie "),         // 0x3e
	[]uint8("Hun "),         // 0x3f
	[]uint8("Yu "),          // 0x40
	[]uint8("Mao "),         // 0x41
	[]uint8("Mei "),         // 0x42
	[]uint8("Chun "),        // 0x43
	[]uint8("Xuan "),        // 0x44
	[]uint8("Ti "),          // 0x45
	[]uint8("Xing "),        // 0x46
	[]uint8("Dai "),         // 0x47
	[]uint8("Rou "),         // 0x48
	[]uint8("Min "),         // 0x49
	[]uint8("Zhen "),        // 0x4a
	[]uint8("Wei "),         // 0x4b
	[]uint8("Ruan "),        // 0x4c
	[]uint8("Huan "),        // 0x4d
	[]uint8("Jie "),         // 0x4e
	[]uint8("Chuan "),       // 0x4f
	[]uint8("Jian "),        // 0x50
	[]uint8("Zhuan "),       // 0x51
	[]uint8("Yang "),        // 0x52
	[]uint8("Lian "),        // 0x53
	[]uint8("Quan "),        // 0x54
	[]uint8("Xia "),         // 0x55
	[]uint8("Duan "),        // 0x56
	[]uint8("Yuan "),        // 0x57
	[]uint8("Ye "),          // 0x58
	[]uint8("Nao "),         // 0x59
	[]uint8("Hu "),          // 0x5a
	[]uint8("Ying "),        // 0x5b
	[]uint8("Yu "),          // 0x5c
	[]uint8("Huang "),       // 0x5d
	[]uint8("Rui "),         // 0x5e
	[]uint8("Se "),          // 0x5f
	[]uint8("Liu "),         // 0x60
	[]uint8("Shi "),         // 0x61
	[]uint8("Rong "),        // 0x62
	[]uint8("Suo "),         // 0x63
	[]uint8("Yao "),         // 0x64
	[]uint8("Wen "),         // 0x65
	[]uint8("Wu "),          // 0x66
	[]uint8("Jin "),         // 0x67
	[]uint8("Jin "),         // 0x68
	[]uint8("Ying "),        // 0x69
	[]uint8("Ma "),          // 0x6a
	[]uint8("Tao "),         // 0x6b
	[]uint8("Liu "),         // 0x6c
	[]uint8("Tang "),        // 0x6d
	[]uint8("Li "),          // 0x6e
	[]uint8("Lang "),        // 0x6f
	[]uint8("Gui "),         // 0x70
	[]uint8("Zhen "),        // 0x71
	[]uint8("Qiang "),       // 0x72
	[]uint8("Cuo "),         // 0x73
	[]uint8("Jue "),         // 0x74
	[]uint8("Zhao "),        // 0x75
	[]uint8("Yao "),         // 0x76
	[]uint8("Ai "),          // 0x77
	[]uint8("Bin "),         // 0x78
	[]uint8("Tu "),          // 0x79
	[]uint8("Chang "),       // 0x7a
	[]uint8("Kun "),         // 0x7b
	[]uint8("Zhuan "),       // 0x7c
	[]uint8("Cong "),        // 0x7d
	[]uint8("Jin "),         // 0x7e
	[]uint8("Yi "),          // 0x7f
	[]uint8("Cui "),         // 0x80
	[]uint8("Cong "),        // 0x81
	[]uint8("Qi "),          // 0x82
	[]uint8("Li "),          // 0x83
	[]uint8("Ying "),        // 0x84
	[]uint8("Suo "),         // 0x85
	[]uint8("Qiu "),         // 0x86
	[]uint8("Xuan "),        // 0x87
	[]uint8("Ao "),          // 0x88
	[]uint8("Lian "),        // 0x89
	[]uint8("Man "),         // 0x8a
	[]uint8("Zhang "),       // 0x8b
	[]uint8("Yin "),         // 0x8c
	[]uint8("[?] "),         // 0x8d
	[]uint8("Ying "),        // 0x8e
	[]uint8("Zhi "),         // 0x8f
	[]uint8("Lu "),          // 0x90
	[]uint8("Wu "),          // 0x91
	[]uint8("Deng "),        // 0x92
	[]uint8("Xiou "),        // 0x93
	[]uint8("Zeng "),        // 0x94
	[]uint8("Xun "),         // 0x95
	[]uint8("Qu "),          // 0x96
	[]uint8("Dang "),        // 0x97
	[]uint8("Lin "),         // 0x98
	[]uint8("Liao "),        // 0x99
	[]uint8("Qiong "),       // 0x9a
	[]uint8("Su "),          // 0x9b
	[]uint8("Huang "),       // 0x9c
	[]uint8("Gui "),         // 0x9d
	[]uint8("Pu "),          // 0x9e
	[]uint8("Jing "),        // 0x9f
	[]uint8("Fan "),         // 0xa0
	[]uint8("Jin "),         // 0xa1
	[]uint8("Liu "),         // 0xa2
	[]uint8("Ji "),          // 0xa3
	[]uint8("[?] "),         // 0xa4
	[]uint8("Jing "),        // 0xa5
	[]uint8("Ai "),          // 0xa6
	[]uint8("Bi "),          // 0xa7
	[]uint8("Can "),         // 0xa8
	[]uint8("Qu "),          // 0xa9
	[]uint8("Zao "),         // 0xaa
	[]uint8("Dang "),        // 0xab
	[]uint8("Jiao "),        // 0xac
	[]uint8("Gun "),         // 0xad
	[]uint8("Tan "),         // 0xae
	[]uint8("Hui "),         // 0xaf
	[]uint8("Huan "),        // 0xb0
	[]uint8("Se "),          // 0xb1
	[]uint8("Sui "),         // 0xb2
	[]uint8("Tian "),        // 0xb3
	[]uint8("[?] "),         // 0xb4
	[]uint8("Yu "),          // 0xb5
	[]uint8("Jin "),         // 0xb6
	[]uint8("Lu "),          // 0xb7
	[]uint8("Bin "),         // 0xb8
	[]uint8("Shou "),        // 0xb9
	[]uint8("Wen "),         // 0xba
	[]uint8("Zui "),         // 0xbb
	[]uint8("Lan "),         // 0xbc
	[]uint8("Xi "),          // 0xbd
	[]uint8("Ji "),          // 0xbe
	[]uint8("Xuan "),        // 0xbf
	[]uint8("Ruan "),        // 0xc0
	[]uint8("Huo "),         // 0xc1
	[]uint8("Gai "),         // 0xc2
	[]uint8("Lei "),         // 0xc3
	[]uint8("Du "),          // 0xc4
	[]uint8("Li "),          // 0xc5
	[]uint8("Zhi "),         // 0xc6
	[]uint8("Rou "),         // 0xc7
	[]uint8("Li "),          // 0xc8
	[]uint8("Zan "),         // 0xc9
	[]uint8("Qiong "),       // 0xca
	[]uint8("Zhe "),         // 0xcb
	[]uint8("Gui "),         // 0xcc
	[]uint8("Sui "),         // 0xcd
	[]uint8("La "),          // 0xce
	[]uint8("Long "),        // 0xcf
	[]uint8("Lu "),          // 0xd0
	[]uint8("Li "),          // 0xd1
	[]uint8("Zan "),         // 0xd2
	[]uint8("Lan "),         // 0xd3
	[]uint8("Ying "),        // 0xd4
	[]uint8("Mi "),          // 0xd5
	[]uint8("Xiang "),       // 0xd6
	[]uint8("Xi "),          // 0xd7
	[]uint8("Guan "),        // 0xd8
	[]uint8("Dao "),         // 0xd9
	[]uint8("Zan "),         // 0xda
	[]uint8("Huan "),        // 0xdb
	[]uint8("Gua "),         // 0xdc
	[]uint8("Bo "),          // 0xdd
	[]uint8("Die "),         // 0xde
	[]uint8("Bao "),         // 0xdf
	[]uint8("Hu "),          // 0xe0
	[]uint8("Zhi "),         // 0xe1
	[]uint8("Piao "),        // 0xe2
	[]uint8("Ban "),         // 0xe3
	[]uint8("Rang "),        // 0xe4
	[]uint8("Li "),          // 0xe5
	[]uint8("Wa "),          // 0xe6
	[]uint8("Dekaguramu "),  // 0xe7
	[]uint8("Jiang "),       // 0xe8
	[]uint8("Qian "),        // 0xe9
	[]uint8("Fan "),         // 0xea
	[]uint8("Pen "),         // 0xeb
	[]uint8("Fang "),        // 0xec
	[]uint8("Dan "),         // 0xed
	[]uint8("Weng "),        // 0xee
	[]uint8("Ou "),          // 0xef
	[]uint8("Deshiguramu "), // 0xf0
	[]uint8("Miriguramu "),  // 0xf1
	[]uint8("Thon "),        // 0xf2
	[]uint8("Hu "),          // 0xf3
	[]uint8("Ling "),        // 0xf4
	[]uint8("Yi "),          // 0xf5
	[]uint8("Ping "),        // 0xf6
	[]uint8("Ci "),          // 0xf7
	[]uint8("Hekutogura "),  // 0xf8
	[]uint8("Juan "),        // 0xf9
	[]uint8("Chang "),       // 0xfa
	[]uint8("Chi "),         // 0xfb
	[]uint8("Sarake "),      // 0xfc
	[]uint8("Dang "),        // 0xfd
	[]uint8("Meng "),        // 0xfe
	[]uint8("Pou "),         // 0xff
}
