package table

var x081 = [][]uint8{
	[]uint8("Cheng "),      // 0x00
	[]uint8("Tiao "),       // 0x01
	[]uint8("Zhi "),        // 0x02
	[]uint8("Cui "),        // 0x03
	[]uint8("Mei "),        // 0x04
	[]uint8("Xie "),        // 0x05
	[]uint8("Cui "),        // 0x06
	[]uint8("Xie "),        // 0x07
	[]uint8("Mo "),         // 0x08
	[]uint8("Mai "),        // 0x09
	[]uint8("Ji "),         // 0x0a
	[]uint8("Obiyaakasu "), // 0x0b
	[]uint8("[?] "),        // 0x0c
	[]uint8("Kuai "),       // 0x0d
	[]uint8("Sa "),         // 0x0e
	[]uint8("Zang "),       // 0x0f
	[]uint8("Qi "),         // 0x10
	[]uint8("Nao "),        // 0x11
	[]uint8("Mi "),         // 0x12
	[]uint8("Nong "),       // 0x13
	[]uint8("Luan "),       // 0x14
	[]uint8("Wan "),        // 0x15
	[]uint8("Bo "),         // 0x16
	[]uint8("Wen "),        // 0x17
	[]uint8("Guan "),       // 0x18
	[]uint8("Qiu "),        // 0x19
	[]uint8("Jiao "),       // 0x1a
	[]uint8("Jing "),       // 0x1b
	[]uint8("Rou "),        // 0x1c
	[]uint8("Heng "),       // 0x1d
	[]uint8("Cuo "),        // 0x1e
	[]uint8("Lie "),        // 0x1f
	[]uint8("Shan "),       // 0x20
	[]uint8("Ting "),       // 0x21
	[]uint8("Mei "),        // 0x22
	[]uint8("Chun "),       // 0x23
	[]uint8("Shen "),       // 0x24
	[]uint8("Xie "),        // 0x25
	[]uint8("De "),         // 0x26
	[]uint8("Zui "),        // 0x27
	[]uint8("Cu "),         // 0x28
	[]uint8("Xiu "),        // 0x29
	[]uint8("Xin "),        // 0x2a
	[]uint8("Tuo "),        // 0x2b
	[]uint8("Pao "),        // 0x2c
	[]uint8("Cheng "),      // 0x2d
	[]uint8("Nei "),        // 0x2e
	[]uint8("Fu "),         // 0x2f
	[]uint8("Dou "),        // 0x30
	[]uint8("Tuo "),        // 0x31
	[]uint8("Niao "),       // 0x32
	[]uint8("Noy "),        // 0x33
	[]uint8("Pi "),         // 0x34
	[]uint8("Gu "),         // 0x35
	[]uint8("Gua "),        // 0x36
	[]uint8("Li "),         // 0x37
	[]uint8("Lian "),       // 0x38
	[]uint8("Zhang "),      // 0x39
	[]uint8("Cui "),        // 0x3a
	[]uint8("Jie "),        // 0x3b
	[]uint8("Liang "),      // 0x3c
	[]uint8("Zhou "),       // 0x3d
	[]uint8("Pi "),         // 0x3e
	[]uint8("Biao "),       // 0x3f
	[]uint8("Lun "),        // 0x40
	[]uint8("Pian "),       // 0x41
	[]uint8("Guo "),        // 0x42
	[]uint8("Kui "),        // 0x43
	[]uint8("Chui "),       // 0x44
	[]uint8("Dan "),        // 0x45
	[]uint8("Tian "),       // 0x46
	[]uint8("Nei "),        // 0x47
	[]uint8("Jing "),       // 0x48
	[]uint8("Jie "),        // 0x49
	[]uint8("La "),         // 0x4a
	[]uint8("Yi "),         // 0x4b
	[]uint8("An "),         // 0x4c
	[]uint8("Ren "),        // 0x4d
	[]uint8("Shen "),       // 0x4e
	[]uint8("Chuo "),       // 0x4f
	[]uint8("Fu "),         // 0x50
	[]uint8("Fu "),         // 0x51
	[]uint8("Ju "),         // 0x52
	[]uint8("Fei "),        // 0x53
	[]uint8("Qiang "),      // 0x54
	[]uint8("Wan "),        // 0x55
	[]uint8("Dong "),       // 0x56
	[]uint8("Pi "),         // 0x57
	[]uint8("Guo "),        // 0x58
	[]uint8("Zong "),       // 0x59
	[]uint8("Ding "),       // 0x5a
	[]uint8("Wu "),         // 0x5b
	[]uint8("Mei "),        // 0x5c
	[]uint8("Ruan "),       // 0x5d
	[]uint8("Zhuan "),      // 0x5e
	[]uint8("Zhi "),        // 0x5f
	[]uint8("Cou "),        // 0x60
	[]uint8("Gua "),        // 0x61
	[]uint8("Ou "),         // 0x62
	[]uint8("Di "),         // 0x63
	[]uint8("An "),         // 0x64
	[]uint8("Xing "),       // 0x65
	[]uint8("Nao "),        // 0x66
	[]uint8("Yu "),         // 0x67
	[]uint8("Chuan "),      // 0x68
	[]uint8("Nan "),        // 0x69
	[]uint8("Yun "),        // 0x6a
	[]uint8("Zhong "),      // 0x6b
	[]uint8("Rou "),        // 0x6c
	[]uint8("E "),          // 0x6d
	[]uint8("Sai "),        // 0x6e
	[]uint8("Tu "),         // 0x6f
	[]uint8("Yao "),        // 0x70
	[]uint8("Jian "),       // 0x71
	[]uint8("Wei "),        // 0x72
	[]uint8("Jiao "),       // 0x73
	[]uint8("Yu "),         // 0x74
	[]uint8("Jia "),        // 0x75
	[]uint8("Duan "),       // 0x76
	[]uint8("Bi "),         // 0x77
	[]uint8("Chang "),      // 0x78
	[]uint8("Fu "),         // 0x79
	[]uint8("Xian "),       // 0x7a
	[]uint8("Ni "),         // 0x7b
	[]uint8("Mian "),       // 0x7c
	[]uint8("Wa "),         // 0x7d
	[]uint8("Teng "),       // 0x7e
	[]uint8("Tui "),        // 0x7f
	[]uint8("Bang "),       // 0x80
	[]uint8("Qian "),       // 0x81
	[]uint8("Lu "),         // 0x82
	[]uint8("Wa "),         // 0x83
	[]uint8("Sou "),        // 0x84
	[]uint8("Tang "),       // 0x85
	[]uint8("Su "),         // 0x86
	[]uint8("Zhui "),       // 0x87
	[]uint8("Ge "),         // 0x88
	[]uint8("Yi "),         // 0x89
	[]uint8("Bo "),         // 0x8a
	[]uint8("Liao "),       // 0x8b
	[]uint8("Ji "),         // 0x8c
	[]uint8("Pi "),         // 0x8d
	[]uint8("Xie "),        // 0x8e
	[]uint8("Gao "),        // 0x8f
	[]uint8("Lu "),         // 0x90
	[]uint8("Bin "),        // 0x91
	[]uint8("Ou "),         // 0x92
	[]uint8("Chang "),      // 0x93
	[]uint8("Lu "),         // 0x94
	[]uint8("Guo "),        // 0x95
	[]uint8("Pang "),       // 0x96
	[]uint8("Chuai "),      // 0x97
	[]uint8("Piao "),       // 0x98
	[]uint8("Jiang "),      // 0x99
	[]uint8("Fu "),         // 0x9a
	[]uint8("Tang "),       // 0x9b
	[]uint8("Mo "),         // 0x9c
	[]uint8("Xi "),         // 0x9d
	[]uint8("Zhuan "),      // 0x9e
	[]uint8("Lu "),         // 0x9f
	[]uint8("Jiao "),       // 0xa0
	[]uint8("Ying "),       // 0xa1
	[]uint8("Lu "),         // 0xa2
	[]uint8("Zhi "),        // 0xa3
	[]uint8("Tara "),       // 0xa4
	[]uint8("Chun "),       // 0xa5
	[]uint8("Lian "),       // 0xa6
	[]uint8("Tong "),       // 0xa7
	[]uint8("Peng "),       // 0xa8
	[]uint8("Ni "),         // 0xa9
	[]uint8("Zha "),        // 0xaa
	[]uint8("Liao "),       // 0xab
	[]uint8("Cui "),        // 0xac
	[]uint8("Gui "),        // 0xad
	[]uint8("Xiao "),       // 0xae
	[]uint8("Teng "),       // 0xaf
	[]uint8("Fan "),        // 0xb0
	[]uint8("Zhi "),        // 0xb1
	[]uint8("Jiao "),       // 0xb2
	[]uint8("Shan "),       // 0xb3
	[]uint8("Wu "),         // 0xb4
	[]uint8("Cui "),        // 0xb5
	[]uint8("Run "),        // 0xb6
	[]uint8("Xiang "),      // 0xb7
	[]uint8("Sui "),        // 0xb8
	[]uint8("Fen "),        // 0xb9
	[]uint8("Ying "),       // 0xba
	[]uint8("Tan "),        // 0xbb
	[]uint8("Zhua "),       // 0xbc
	[]uint8("Dan "),        // 0xbd
	[]uint8("Kuai "),       // 0xbe
	[]uint8("Nong "),       // 0xbf
	[]uint8("Tun "),        // 0xc0
	[]uint8("Lian "),       // 0xc1
	[]uint8("Bi "),         // 0xc2
	[]uint8("Yong "),       // 0xc3
	[]uint8("Jue "),        // 0xc4
	[]uint8("Chu "),        // 0xc5
	[]uint8("Yi "),         // 0xc6
	[]uint8("Juan "),       // 0xc7
	[]uint8("La "),         // 0xc8
	[]uint8("Lian "),       // 0xc9
	[]uint8("Sao "),        // 0xca
	[]uint8("Tun "),        // 0xcb
	[]uint8("Gu "),         // 0xcc
	[]uint8("Qi "),         // 0xcd
	[]uint8("Cui "),        // 0xce
	[]uint8("Bin "),        // 0xcf
	[]uint8("Xun "),        // 0xd0
	[]uint8("Ru "),         // 0xd1
	[]uint8("Huo "),        // 0xd2
	[]uint8("Zang "),       // 0xd3
	[]uint8("Xian "),       // 0xd4
	[]uint8("Biao "),       // 0xd5
	[]uint8("Xing "),       // 0xd6
	[]uint8("Kuan "),       // 0xd7
	[]uint8("La "),         // 0xd8
	[]uint8("Yan "),        // 0xd9
	[]uint8("Lu "),         // 0xda
	[]uint8("Huo "),        // 0xdb
	[]uint8("Zang "),       // 0xdc
	[]uint8("Luo "),        // 0xdd
	[]uint8("Qu "),         // 0xde
	[]uint8("Zang "),       // 0xdf
	[]uint8("Luan "),       // 0xe0
	[]uint8("Ni "),         // 0xe1
	[]uint8("Zang "),       // 0xe2
	[]uint8("Chen "),       // 0xe3
	[]uint8("Qian "),       // 0xe4
	[]uint8("Wo "),         // 0xe5
	[]uint8("Guang "),      // 0xe6
	[]uint8("Zang "),       // 0xe7
	[]uint8("Lin "),        // 0xe8
	[]uint8("Guang "),      // 0xe9
	[]uint8("Zi "),         // 0xea
	[]uint8("Jiao "),       // 0xeb
	[]uint8("Nie "),        // 0xec
	[]uint8("Chou "),       // 0xed
	[]uint8("Ji "),         // 0xee
	[]uint8("Gao "),        // 0xef
	[]uint8("Chou "),       // 0xf0
	[]uint8("Mian "),       // 0xf1
	[]uint8("Nie "),        // 0xf2
	[]uint8("Zhi "),        // 0xf3
	[]uint8("Zhi "),        // 0xf4
	[]uint8("Ge "),         // 0xf5
	[]uint8("Jian "),       // 0xf6
	[]uint8("Die "),        // 0xf7
	[]uint8("Zhi "),        // 0xf8
	[]uint8("Xiu "),        // 0xf9
	[]uint8("Tai "),        // 0xfa
	[]uint8("Zhen "),       // 0xfb
	[]uint8("Jiu "),        // 0xfc
	[]uint8("Xian "),       // 0xfd
	[]uint8("Yu "),         // 0xfe
	[]uint8("Cha "),        // 0xff
}
