package table

var x091 = [][]uint8{
	[]uint8("Ruo "),        // 0x00
	[]uint8("Bei "),        // 0x01
	[]uint8("E "),          // 0x02
	[]uint8("Yu "),         // 0x03
	[]uint8("Juan "),       // 0x04
	[]uint8("Yu "),         // 0x05
	[]uint8("Yun "),        // 0x06
	[]uint8("Hou "),        // 0x07
	[]uint8("Kui "),        // 0x08
	[]uint8("Xiang "),      // 0x09
	[]uint8("Xiang "),      // 0x0a
	[]uint8("Sou "),        // 0x0b
	[]uint8("Tang "),       // 0x0c
	[]uint8("Ming "),       // 0x0d
	[]uint8("Xi "),         // 0x0e
	[]uint8("Ru "),         // 0x0f
	[]uint8("Chu "),        // 0x10
	[]uint8("Zi "),         // 0x11
	[]uint8("Zou "),        // 0x12
	[]uint8("Ju "),         // 0x13
	[]uint8("Wu "),         // 0x14
	[]uint8("Xiang "),      // 0x15
	[]uint8("Yun "),        // 0x16
	[]uint8("Hao "),        // 0x17
	[]uint8("Yong "),       // 0x18
	[]uint8("Bi "),         // 0x19
	[]uint8("Mo "),         // 0x1a
	[]uint8("Chao "),       // 0x1b
	[]uint8("Fu "),         // 0x1c
	[]uint8("Liao "),       // 0x1d
	[]uint8("Yin "),        // 0x1e
	[]uint8("Zhuan "),      // 0x1f
	[]uint8("Hu "),         // 0x20
	[]uint8("Qiao "),       // 0x21
	[]uint8("Yan "),        // 0x22
	[]uint8("Zhang "),      // 0x23
	[]uint8("Fan "),        // 0x24
	[]uint8("Qiao "),       // 0x25
	[]uint8("Xu "),         // 0x26
	[]uint8("Deng "),       // 0x27
	[]uint8("Bi "),         // 0x28
	[]uint8("Xin "),        // 0x29
	[]uint8("Bi "),         // 0x2a
	[]uint8("Ceng "),       // 0x2b
	[]uint8("Wei "),        // 0x2c
	[]uint8("Zheng "),      // 0x2d
	[]uint8("Mao "),        // 0x2e
	[]uint8("Shan "),       // 0x2f
	[]uint8("Lin "),        // 0x30
	[]uint8("Po "),         // 0x31
	[]uint8("Dan "),        // 0x32
	[]uint8("Meng "),       // 0x33
	[]uint8("Ye "),         // 0x34
	[]uint8("Cao "),        // 0x35
	[]uint8("Kuai "),       // 0x36
	[]uint8("Feng "),       // 0x37
	[]uint8("Meng "),       // 0x38
	[]uint8("Zou "),        // 0x39
	[]uint8("Kuang "),      // 0x3a
	[]uint8("Lian "),       // 0x3b
	[]uint8("Zan "),        // 0x3c
	[]uint8("Chan "),       // 0x3d
	[]uint8("You "),        // 0x3e
	[]uint8("Qi "),         // 0x3f
	[]uint8("Yan "),        // 0x40
	[]uint8("Chan "),       // 0x41
	[]uint8("Zan "),        // 0x42
	[]uint8("Ling "),       // 0x43
	[]uint8("Huan "),       // 0x44
	[]uint8("Xi "),         // 0x45
	[]uint8("Feng "),       // 0x46
	[]uint8("Zan "),        // 0x47
	[]uint8("Li "),         // 0x48
	[]uint8("You "),        // 0x49
	[]uint8("Ding "),       // 0x4a
	[]uint8("Qiu "),        // 0x4b
	[]uint8("Zhuo "),       // 0x4c
	[]uint8("Pei "),        // 0x4d
	[]uint8("Zhou "),       // 0x4e
	[]uint8("Yi "),         // 0x4f
	[]uint8("Hang "),       // 0x50
	[]uint8("Yu "),         // 0x51
	[]uint8("Jiu "),        // 0x52
	[]uint8("Yan "),        // 0x53
	[]uint8("Zui "),        // 0x54
	[]uint8("Mao "),        // 0x55
	[]uint8("Dan "),        // 0x56
	[]uint8("Xu "),         // 0x57
	[]uint8("Tou "),        // 0x58
	[]uint8("Zhen "),       // 0x59
	[]uint8("Fen "),        // 0x5a
	[]uint8("Sakenomoto "), // 0x5b
	[]uint8("[?] "),        // 0x5c
	[]uint8("Yun "),        // 0x5d
	[]uint8("Tai "),        // 0x5e
	[]uint8("Tian "),       // 0x5f
	[]uint8("Qia "),        // 0x60
	[]uint8("Tuo "),        // 0x61
	[]uint8("Zuo "),        // 0x62
	[]uint8("Han "),        // 0x63
	[]uint8("Gu "),         // 0x64
	[]uint8("Su "),         // 0x65
	[]uint8("Po "),         // 0x66
	[]uint8("Chou "),       // 0x67
	[]uint8("Zai "),        // 0x68
	[]uint8("Ming "),       // 0x69
	[]uint8("Luo "),        // 0x6a
	[]uint8("Chuo "),       // 0x6b
	[]uint8("Chou "),       // 0x6c
	[]uint8("You "),        // 0x6d
	[]uint8("Tong "),       // 0x6e
	[]uint8("Zhi "),        // 0x6f
	[]uint8("Xian "),       // 0x70
	[]uint8("Jiang "),      // 0x71
	[]uint8("Cheng "),      // 0x72
	[]uint8("Yin "),        // 0x73
	[]uint8("Tu "),         // 0x74
	[]uint8("Xiao "),       // 0x75
	[]uint8("Mei "),        // 0x76
	[]uint8("Ku "),         // 0x77
	[]uint8("Suan "),       // 0x78
	[]uint8("Lei "),        // 0x79
	[]uint8("Pu "),         // 0x7a
	[]uint8("Zui "),        // 0x7b
	[]uint8("Hai "),        // 0x7c
	[]uint8("Yan "),        // 0x7d
	[]uint8("Xi "),         // 0x7e
	[]uint8("Niang "),      // 0x7f
	[]uint8("Wei "),        // 0x80
	[]uint8("Lu "),         // 0x81
	[]uint8("Lan "),        // 0x82
	[]uint8("Yan "),        // 0x83
	[]uint8("Tao "),        // 0x84
	[]uint8("Pei "),        // 0x85
	[]uint8("Zhan "),       // 0x86
	[]uint8("Chun "),       // 0x87
	[]uint8("Tan "),        // 0x88
	[]uint8("Zui "),        // 0x89
	[]uint8("Chuo "),       // 0x8a
	[]uint8("Cu "),         // 0x8b
	[]uint8("Kun "),        // 0x8c
	[]uint8("Ti "),         // 0x8d
	[]uint8("Mian "),       // 0x8e
	[]uint8("Du "),         // 0x8f
	[]uint8("Hu "),         // 0x90
	[]uint8("Xu "),         // 0x91
	[]uint8("Xing "),       // 0x92
	[]uint8("Tan "),        // 0x93
	[]uint8("Jiu "),        // 0x94
	[]uint8("Chun "),       // 0x95
	[]uint8("Yun "),        // 0x96
	[]uint8("Po "),         // 0x97
	[]uint8("Ke "),         // 0x98
	[]uint8("Sou "),        // 0x99
	[]uint8("Mi "),         // 0x9a
	[]uint8("Quan "),       // 0x9b
	[]uint8("Chou "),       // 0x9c
	[]uint8("Cuo "),        // 0x9d
	[]uint8("Yun "),        // 0x9e
	[]uint8("Yong "),       // 0x9f
	[]uint8("Ang "),        // 0xa0
	[]uint8("Zha "),        // 0xa1
	[]uint8("Hai "),        // 0xa2
	[]uint8("Tang "),       // 0xa3
	[]uint8("Jiang "),      // 0xa4
	[]uint8("Piao "),       // 0xa5
	[]uint8("Shan "),       // 0xa6
	[]uint8("Yu "),         // 0xa7
	[]uint8("Li "),         // 0xa8
	[]uint8("Zao "),        // 0xa9
	[]uint8("Lao "),        // 0xaa
	[]uint8("Yi "),         // 0xab
	[]uint8("Jiang "),      // 0xac
	[]uint8("Pu "),         // 0xad
	[]uint8("Jiao "),       // 0xae
	[]uint8("Xi "),         // 0xaf
	[]uint8("Tan "),        // 0xb0
	[]uint8("Po "),         // 0xb1
	[]uint8("Nong "),       // 0xb2
	[]uint8("Yi "),         // 0xb3
	[]uint8("Li "),         // 0xb4
	[]uint8("Ju "),         // 0xb5
	[]uint8("Jiao "),       // 0xb6
	[]uint8("Yi "),         // 0xb7
	[]uint8("Niang "),      // 0xb8
	[]uint8("Ru "),         // 0xb9
	[]uint8("Xun "),        // 0xba
	[]uint8("Chou "),       // 0xbb
	[]uint8("Yan "),        // 0xbc
	[]uint8("Ling "),       // 0xbd
	[]uint8("Mi "),         // 0xbe
	[]uint8("Mi "),         // 0xbf
	[]uint8("Niang "),      // 0xc0
	[]uint8("Xin "),        // 0xc1
	[]uint8("Jiao "),       // 0xc2
	[]uint8("Xi "),         // 0xc3
	[]uint8("Mi "),         // 0xc4
	[]uint8("Yan "),        // 0xc5
	[]uint8("Bian "),       // 0xc6
	[]uint8("Cai "),        // 0xc7
	[]uint8("Shi "),        // 0xc8
	[]uint8("You "),        // 0xc9
	[]uint8("Shi "),        // 0xca
	[]uint8("Shi "),        // 0xcb
	[]uint8("Li "),         // 0xcc
	[]uint8("Zhong "),      // 0xcd
	[]uint8("Ye "),         // 0xce
	[]uint8("Liang "),      // 0xcf
	[]uint8("Li "),         // 0xd0
	[]uint8("Jin "),        // 0xd1
	[]uint8("Jin "),        // 0xd2
	[]uint8("Qiu "),        // 0xd3
	[]uint8("Yi "),         // 0xd4
	[]uint8("Diao "),       // 0xd5
	[]uint8("Dao "),        // 0xd6
	[]uint8("Zhao "),       // 0xd7
	[]uint8("Ding "),       // 0xd8
	[]uint8("Po "),         // 0xd9
	[]uint8("Qiu "),        // 0xda
	[]uint8("He "),         // 0xdb
	[]uint8("Fu "),         // 0xdc
	[]uint8("Zhen "),       // 0xdd
	[]uint8("Zhi "),        // 0xde
	[]uint8("Ba "),         // 0xdf
	[]uint8("Luan "),       // 0xe0
	[]uint8("Fu "),         // 0xe1
	[]uint8("Nai "),        // 0xe2
	[]uint8("Diao "),       // 0xe3
	[]uint8("Shan "),       // 0xe4
	[]uint8("Qiao "),       // 0xe5
	[]uint8("Kou "),        // 0xe6
	[]uint8("Chuan "),      // 0xe7
	[]uint8("Zi "),         // 0xe8
	[]uint8("Fan "),        // 0xe9
	[]uint8("Yu "),         // 0xea
	[]uint8("Hua "),        // 0xeb
	[]uint8("Han "),        // 0xec
	[]uint8("Gong "),       // 0xed
	[]uint8("Qi "),         // 0xee
	[]uint8("Mang "),       // 0xef
	[]uint8("Ri "),         // 0xf0
	[]uint8("Di "),         // 0xf1
	[]uint8("Si "),         // 0xf2
	[]uint8("Xi "),         // 0xf3
	[]uint8("Yi "),         // 0xf4
	[]uint8("Chai "),       // 0xf5
	[]uint8("Shi "),        // 0xf6
	[]uint8("Tu "),         // 0xf7
	[]uint8("Xi "),         // 0xf8
	[]uint8("Nu "),         // 0xf9
	[]uint8("Qian "),       // 0xfa
	[]uint8("Ishiyumi "),   // 0xfb
	[]uint8("Jian "),       // 0xfc
	[]uint8("Pi "),         // 0xfd
	[]uint8("Ye "),         // 0xfe
	[]uint8("Yin "),        // 0xff
}
